import '@styles/index.css'
import '@styles/home.css'
import '@styles/header.css'
import '@styles/control-bar.css'
import '@styles/control-panel.css'
import '@styles/song-item.css'
import '@styles/load-more.css'
